<?php

return [
    'C' => 'Chișinău',
    'BL' => 'Bălți',
    'AN' => 'Anenii Noi',
    'BS' => 'Basarabeasca',
    'BR' => 'Briceni',
    'CH' => 'Cahul',
    'CT' => 'Cantemir',
    'CL' => 'Călărași',
    'CS' => 'Căușeni',
    'CM' => 'Cimișlia',
    'CR' => 'Criuleni',
    'DN' => 'Dondușeni',
    'DR' => 'Drochia',
    'DB' => 'Dubăsari',
    'ED' => 'Edineț',
    'FL' => 'Fălești',
    'FR' => 'Florești',
    'GE' => 'UTA Găgăuzia',
    'GL' => 'Glodeni',
    'HN' => 'Hîncești',
    'IL' => 'Ialoveni',
    'LV' => 'Leova',
    'NS' => 'Nisporeni',
    'OC' => 'Ocnița',
    'OR' => 'Orhei',
    'RZ' => 'Rezina',
    'RS' => 'Rîșcani',
    'SG' => 'Sîngerei',
    'SR' => 'Soroca',
    'ST' => 'Strășeni',
    'SD' => 'Șoldănești',
    'SV' => 'Ștefan Vodă',
    'TR' => 'Taraclia',
    'TL' => 'Telenești',
    'UN' => 'Ungheni',
];
